#!/bin/bash

BRIDGE=$1
DUMMY_IFACE="${BRIDGE}mon"

ovs-vsctl add-br "$BRIDGE"
if [ "$?" -ne 0 ]; then
    exit 1
fi

ip link set "$BRIDGE" up

modprobe dummy || true
ip link add ${DUMMY_IFACE} type dummy 
ip link set "${DUMMY_IFACE}" up

ovs-vsctl add-port $BRIDGE ${DUMMY_IFACE}

ovs-vsctl -- --id=@p get port ${DUMMY_IFACE} \
    -- --id=@m create mirror name=${BRIDGE}mirror select-all=true output-port=@p \
    -- set bridge ${BRIDGE} mirrors=@m

exit 0