#!/bin/bash

set -e

BRIDGE=$1
DUMMY_IFACE="${BRIDGE}mon"

ovs-vsctl clear bridge $BRIDGE mirrors

ovs-vsctl del-port $BRIDGE ${DUMMY_IFACE}

ip link delete "${DUMMY_IFACE}"

ovs-vsctl del-br "$BRIDGE"
